//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecordMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecordMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resourses.RecordMessages", typeof(RecordMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} was added to room {1} by user {1}.
        ///.
        /// </summary>
        internal static string AddUserToRoom {
            get {
                return ResourceManager.GetString("AddUserToRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} was added to text chat {1} in room {2} by user {3}.
        ///.
        /// </summary>
        internal static string AddUserToTextChat {
            get {
                return ResourceManager.GetString("AddUserToTextChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role of user {0} was changed from {1} to {2} in room {3} by user {4}.
        ///.
        /// </summary>
        internal static string ChangeUserRoleType {
            get {
                return ResourceManager.GetString("ChangeUserRoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} was removed from room {1} by user {2}.
        ///.
        /// </summary>
        internal static string DeleteUserFromRoom {
            get {
                return ResourceManager.GetString("DeleteUserFromRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} was removed to text chat {1} in room {2} by user {3}..
        /// </summary>
        internal static string DeleteUserFromTextChat {
            get {
                return ResourceManager.GetString("DeleteUserFromTextChat", resourceCulture);
            }
        }
    }
}
